"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import sys
sys.setrecursionlimit(50000)


APP = ['gui.py']
DATA_FILES = ['CosmoSuite.py',
 'MakefileDict.py',
 'ParamsDict.py',
 'StdoutDirector.py',
 'Tooltip.py',
 'TooltipDict.py',
 'VerticalScrolledFrame.py',
 'ViewLog.py',
 'KThread.py'
]

OPTIONS = {'argv_emulation': True,
            'site_packages': True,
            'resources':['readme.txt', '/Users/mahmoud/Documents/UWC_AstroGroup/UWC_Hashim-PhD/Codes/CosmoSuite_App/CosmoSuite/label_photos/'],
            'includes': ['matplotlib', 'paramiko'],
            'packages': ['matplotlib', 'paramiko'],
            'iconfile': '/Users/mahmoud/Documents/UWC_AstroGroup/UWC_Hashim-PhD/Codes/CosmoSuite_App/CosmoSuite/CosmoSuite.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
